---

- name: add stable nginx repository ppa
  apt_repository: repo='ppa:nginx/stable'

- name: install nginx
  apt: pkg=nginx state=installed update_cache=yes cache_valid_time=3600

- name: ensure directory /var/www
  file: path=/var/www state=directory owner=root group=root mode=0755

- name: ensure directory /var/www/common
  file: path=/var/www/common state=directory owner=www-data group=www-data mode=0755

- name: ensure nginx cache directory /var/cache/nginx
  file: >
    path=/var/cache/nginx state=directory
    owner=root group=root mode=0755

- name: recreate sites-available and sites-enabled directories
  file: >
    path=/etc/nginx/{{ item }} state=directory
    owner=root group=root mode=0755
  with_items:
    - sites-available
    - sites-enabled

- name: ensure directory /etc/nginx/conf.d is present
  file: path=/etc/nginx/conf.d state=directory owner=root group=root mode=0755

- name: add proxy_params mimes.types koi-win koi-utf win-utf
  copy: >
    src=etc-nginx-{{ item }}
    dest=/etc/nginx/{{ item }}
    owner=root group=root mode=0644
  with_items:
    - proxy_params
    - mime.types
    - koi-win
    - koi-utf
    - win-utf

- name: add /etc/nginx/nginx.conf
  template: >
    src=etc-nginx-nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root group=root mode=0644
  notify: nginx reload

- name: add /etc/nginx/sites-available/default
  template: >
    src=etc-nginx-sites-available-default.j2
    dest=/etc/nginx/sites-available/default
    owner=root group=root mode=0644
  notify: nginx reload

- name: symlink 'default' site in sites-enabled
  file: >
    src=/etc/nginx/sites-available/default
    dest=/etc/nginx/sites-enabled/default
    owner=root group=root state=link
  notify: nginx reload

- name: ensure nginx started
  service: name=nginx state=started enabled=yes

- name: open port 80 for Nginx
  shell: "ufw allow 80"