---

- name: add chris-lea-nodejs-legacy repository ppa
  apt_repository: repo='ppa:chris-lea/node.js'

- name: install nodejs
  apt: >
    pkg=nodejs{{ nodejs.install.node_version }} state=installed
    update_cache=yes cache_valid_time=3600

#- name: install npm
#  apt: >
#    pkg=npm{{ nodejs.install.npm_version }} state=installed
#    update_cache=yes cache_valid_time=3600
