---

- name: install/ensure fail2ban
  apt: >
    pkg=fail2ban state=installed
    update_cache=yes cache_valid_time=3600

- name: add /etc/fail2ban/jail.local
  template: >
    src=etc-fail2ban-jail.local.j2
    dest=/etc/fail2ban/jail.local
    owner=root group=root mode=0644
  notify:
    - fail2ban restart