---

nginx:

  # Path for proxy cache
  cachePath: "/var/cache/nginx"

  # For a description of each variable see templates/etc-nginx.conf.j2
  config:
    user: "www-data"
    pid: "/var/run/nginx.pid"
    worker_processes: "{{ ansible_processor_cores }}"

    events:
      worker_connections: "4000"
      use: "epoll"
      multi_accept: "on"

    worker_rlimit_nofile: "200000"
    error_log: "/var/log/nginx/nginx.log crit"

    http:
      server_tokens: "off"
      ignore_invalid_headers: "on"
      recursive_error_pages: "on"
      sendfile: "on"
      tcp_nopush: "on"
      tcp_nodelay: "on"
      default_type: "application/octet-stream"
      keepalive_requests: "20"
      keepalive_timeout: "30"
      keepalive_disable: "'msie6'"
      send_timeout: "30"
      max_ranges: "0"
      open_file_cache: "max=1000 inactive=30s"
      open_file_cache_errors: "on"
      open_file_cache_min_uses: "2"
      open_file_cache_valid: "30s"
      if_modified_since: "before"
      server_names_hash_bucket_size: "64"
      reset_timedout_connection: "on"
      add_header: "X-Frame-Options SAMEORIGIN"
      charset: "utf-8"
      source_charset: "utf-8"
      gzip_static: "on"
      gzip: "on"
      gzip_disable: "msi6"
      gzip_http_version: "1.1"
      gzip_vary: "on"
      gzip_comp_level: "3"
      gzip_min_length: "10"
      gzip_proxied: "expired no-cache no-store private auth"
      gzip_types: "text/css text/javascript application/x-javascript text/x-component text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/x-icon image/bmp application/xml application/xml+rss application/vnd.ms-fontobject font/opentype application/x-font-ttf"
      ssl_session_cache: "shared:SSL:10m"
      ssl_session_timeout: "10m"
      proxy_set_header_one: "Host $host"
      proxy_set_header_two: "X-Real-IP $remote_addr"
      proxy_set_header_three: "X-Forwarded-For $proxy_add_x_forwarded_for"
      proxy_hide_header_one: "X-Powered-By"
      proxy_hide_header_two: "X-Frame-Options"
      proxy_buffers: "8 16k"
      proxy_buffer_size: "32k"
      proxy_temp_path: "/var/lib/nginx/proxy"
      proxy_cache_path: "/var/cache/nginx/proxy/ levels=1:2 keys_zone=proxy_short:5m inactive=2m max_size=1G loader_threshold=2592000000 loader_sleep=1 loader_files=100000"
      limit_conn_zone: "$binary_remote_addr zone=connection_limit:10m"
      limit_req_zone: "$binary_remote_addr zone=request_limit:10m  rate=5r/s"
      access_log: "off"
